name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-test.txt
          pip install xgboost jupyter "anyio<4.0.0"
          pip install jinja2<3.1.0
          pip install itsdangerous==2.0.1
          pip install werkzeug==2.0.3
      - name: Build Docker image
        run: docker build -t flight-delay-api .
